[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/lead"
  to = "/.netlify/functions/lead"
  status = 200
  force = true
